name: Rust CD

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Rust Stable
        run: rustup default stable

      - name: Extract release info
        id: extract
        run: |
          RELEASE_TITLE="${{ github.event.release.tag_name }}"
          if [[ $RELEASE_TITLE =~ ^([a-zA-Z0-9_-]+)@([0-9]+\.[0-9]+\.[0-9]+.*) ]]; then
            echo "::set-output name=crate::${BASH_REMATCH[1]}"
          else
            echo "Invalid release title. Expected format: crate@version"
            exit 1
          fi

      - name: Publish crate to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO }}
        run: |
          cargo publish --all-features --manifest-path ./${{ steps.extract.outputs.crate }}/Cargo.toml
