name: Publish Crate

on:
  release:
    types: [published]

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml
  publish-crate:
    name: Publish crate
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository at the published tag
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Install Rust stable
        run: rustup default stable

      - name: Install cargo-release
        run: cargo install cargo-release

      - name: Extract crate name
        id: extract
        run: |
          RELEASE_TAG="${{ github.event.release.tag_name }}"
          if [[ "$RELEASE_TAG" =~ ^([a-zA-Z0-9_-]+)@([0-9]+\.[0-9]+\.[0-9]+.*)$ ]]; then
            echo "crate=${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
          else
            echo "Invalid release tag. Expected format: crate-name@1.2.3"
            exit 1
          fi

      - name: Publish to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO }}
        run: |
          cargo release release \
            --package ${{ steps.extract.outputs.crate }} \
            --skip-bump \
            --skip-tag \
            --publish \
            --execute